void buzzTone(unsigned int freq);
void displayText(const char *text);
void printKey(uint16_t key, const char *info);
void pressKey(uint16_t key);
void releaseKey(uint16_t key);
void writeKey(uint16_t key);
void setupSettings();
void loopMenuMode();
void loopNormalMode();
void loopGenericMode();
void printMode(int m);
void selectMode(int m);
void cancelMode();
void displayMenu(const char *text);